# -*- coding: utf-8 -*-
"""Loan_Approval_Model_Corrected.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eGm5E3wHEsgAHP3m3WqU4X_1Ij5bBVer

# Loan Approval Prediction Model — Corrected Version
Run all cells top to bottom. At the end, all `.pkl` files and `thresholds.json` will be saved and auto-downloaded.
"""

import pandas as pd
import numpy as np
import pickle
import json
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

print('Libraries loaded successfully!')

# Load dataset
df = pd.read_csv('train.csv')
print('Shape:', df.shape)
df.head()

# Check missing values
print(df.isnull().sum())

# Fix Age column
df['Age'] = df['Age'].round().astype(int)

# Fill missing values
df['Married']          = df['Married'].fillna(df['Married'].mode()[0])
df['Education']        = df['Education'].bfill()
df['Employment_Status'] = df['Employment_Status'].ffill()
df['Dependents']       = df['Dependents'].fillna(0)
df['Credit_History']   = df['Credit_History'].fillna(df['Credit_History'].mode()[0])
df['Loan_Amount']      = df['Loan_Amount'].fillna(df['Loan_Amount'].median())
df['Loan_Term']        = df['Loan_Term'].fillna(df['Loan_Term'].mode()[0])

print('Missing values after fill:')
print(df.isnull().sum())

# Save income and loan quantile thresholds BEFORE replacing values
income_q = float(df['Applicant_Income'].quantile())
loan_q   = float(df['Loan_Amount'].quantile())

thresholds = {
    'income_q': income_q,
    'loan_q':   loan_q
}

print(f'Income median threshold : {income_q}')
print(f'Loan amount median      : {loan_q}')

# Label encode Gender, Married, Property_Area and SAVE each encoder
le_gender  = LabelEncoder()
le_married = LabelEncoder()
le_prop    = LabelEncoder()

df['Gender']       = le_gender.fit_transform(df['Gender'].astype(str))
df['Married']      = le_married.fit_transform(df['Married'].astype(str))
df['Property_Area'] = le_prop.fit_transform(df['Property_Area'].astype(str))

print('Gender classes :', le_gender.classes_)
print('Married classes:', le_married.classes_)
print('Property classes:', le_prop.classes_)

# Replace Applicant_Income and Loan_Amount with their quantile (matches original training)
df['Applicant_Income'] = df['Applicant_Income'].quantile()
df['Loan_Amount']      = df['Loan_Amount'].quantile()

# One-hot encode Education and Employment_Status
education_dummies  = pd.get_dummies(df['Education'],         prefix='Education',         drop_first=True)
employment_dummies = pd.get_dummies(df['Employment_Status'],  prefix='Employment_Status',  drop_first=True)

df = df.drop(['Education', 'Employment_Status'], axis=1)
df = pd.concat([df, education_dummies, employment_dummies], axis=1)

# Drop Loan_ID if present
if 'Loan_ID' in df.columns:
    df.drop('Loan_ID', axis=1, inplace=True)

print('Columns after encoding:', list(df.columns))

# Encode target — Loan_Status_Rejected (1 = Rejected, 0 = Approved)
loan_dummies = pd.get_dummies(df['Loan_Status'], prefix='Loan_Status', drop_first=True)
df = df.drop('Loan_Status', axis=1)
df = pd.concat([df, loan_dummies], axis=1)

print('Final columns:', list(df.columns))
print('Target distribution:')
print(df['Loan_Status_Rejected'].value_counts())

# Train/test split
x = df.drop('Loan_Status_Rejected', axis=1)
y = df['Loan_Status_Rejected']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print('Train size:', x_train.shape)
print('Test size :', x_test.shape)

# Train RandomForestClassifier (FIXED from Regressor)
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Model Accuracy: {accuracy * 100:.2f}%')
print()
print(classification_report(y_test, y_pred, target_names=['Approved', 'Rejected']))

# Feature importance — so you can see what drives predictions
feat_imp = pd.Series(model.feature_importances_, index=x.columns)
feat_imp.sort_values(ascending=False).head(10)

# Save all files
pickle.dump(model,      open('model.pkl',      'wb'))
pickle.dump(le_gender,  open('le_gender.pkl',  'wb'))
pickle.dump(le_married, open('le_married.pkl', 'wb'))
pickle.dump(le_prop,    open('le_prop.pkl',    'wb'))

with open('thresholds.json', 'w') as f:
    json.dump(thresholds, f)

print('All files saved:')
print('  model.pkl')
print('  le_gender.pkl')
print('  le_married.pkl')
print('  le_prop.pkl')
print('  thresholds.json')

# Auto-download all files (Colab only)
try:
    from google.colab import files
    files.download('model.pkl')
    files.download('le_gender.pkl')
    files.download('le_married.pkl')
    files.download('le_prop.pkl')
    files.download('thresholds.json')
    print('Downloads started!')
except ImportError:
    print('Not running in Colab — files are saved in your current directory.')
