# -*- coding: utf-8 -*-
"""Customer Behavior Analysis Using XGBoost  .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmgjYuGrwCyZzHUmWa94LFOIT4t689IX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df = pd.read_csv('/content/Ecommerce_Consumer_Behavior_Analysis_Data.csv')
df.describe()

df.dtypes

df['Age'].unique()

df['Brand_Loyalty'].unique()

df['Frequency_of_Purchase'].unique()

df['Device_Used_for_Shopping'].unique()

df['Education_Level'].unique()

df['Customer_Satisfaction'].unique()

df['Location'].unique()

df['Marital_Status'].unique()

df['Payment_Method'].unique()

df['Customer_Loyalty_Program_Member'].unique()

df['Occupation'].unique()

df['Return_Rate'].unique()

df.dtypes

df = df.drop(['Customer_ID'],axis = 1, errors = 'ignore')
df

from sklearn.preprocessing import LabelEncoder
lable = LabelEncoder()
for col in df.columns :
  if df[col].dtypes == 'object':
    df[col] = lable.fit_transform(df[col])

x = df.drop(['Return_Rate_1'],axis = 1)
y = df['Return_Rate_1']

x_train , x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size = 0.2,)

xgb = XGBClassifier()
xgb.fit(x_train,y_train)

y_pred = xgb.predict(x_test)

print("Accuracy score :\n",accuracy_score(y_test,y_pred))

y_pred

from xgboost import plot_tree

plt.figure(figsize=(20,10))
plot_tree(xgb,num_trees =0)
plt.title('Decision Tree')
plt.show()

plt.plot(xgb.feature_importances_)
plt.xticks(np.arange(x.shape[1]),rotation = 90)
plt.title('Predicted value of return rate ')
plt.show()

print(xgb.feature_importances_)
