# -*- coding: utf-8 -*-
"""Mnist_ANN_pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5AEKAn6hxPGSy2_yHgTdII8QIERymwY
"""

import os
import pandas as pd
import matplotlib.pyplot  as plt
import torch
import torch.nn as nn

import torch.optim as optim
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

torch.manual_seed(42)

import kagglehub

# Download latest version
path = kagglehub.dataset_download("matthumphrey/mnist-dataset")

print("Path to dataset files:", path)

for file in os.listdir(path):
  print(file)

file_path = os.path.join(path, "train.csv")
df = pd.read_csv(file_path)
df.head()

df.shape

df.info()
df.describe()

df['label'].value_counts()

# creating the grid of images
fig, axes = plt.subplots(4,4,figsize=(12,10))
fig.suptitle("First 16 images :",fontsize=16)

for i, ax in enumerate(axes.flat):
  image = df.iloc[i,1:].values.reshape(28,28)
  ax.imshow(image, cmap="gray")
  ax.axis("off")
  ax.set_title(f"Label : {df.iloc[i,0]}")
plt.show()

#  splitting for trainig set

x = df.iloc[:,1:].values.astype("float32")
y = df.iloc[:,0].values.astype("int64")

x = x/255

x_train, x_test,y_train ,y_test = train_test_split(
    x,y,test_size=0.2,random_state=42,stratify=y
    )



# create the class for the data
class dataset(Dataset):
  def __init__(self,x,y):
    self.x = torch.tensor(x,dtype=torch.float32)
    self.y = torch.tensor(y,dtype=torch.long)
  def __len__(self):
    return len(self.x)
  def __getitem__(self,idx):
    return self.x[idx],self.y[idx]

train_dataset = dataset(x_train , y_train)
test_dataset = dataset(x_test,y_test)

train_loader = DataLoader(train_dataset,batch_size=64,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=64,shuffle=False)

class module(nn.Module):
      def __init__(self):
        super().__init__()
        # Hidden Layer 1
        self.fc1 = nn.Linear(784,512)
        # Hidden Layer 2
        self.fc2 = nn.Linear(512,256)
        # Hidden Layer 3
        self.fc3 = nn.Linear(256,128)
        # Output Layer
        self.fc4 = nn.Linear(128,10)
        # Activation
        self.relu = nn.ReLU()
      def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)
        x = self.relu(x)
        x = self.fc4(x)
        return x

model = module().to(device)
print(model)



epochs = 10
learning_rate = 0.001

loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr = learning_rate)

for epoch in range(epochs):
  total_epochs = 0
  model.train()
  for feature, label in train_loader:
    # forward pass :
    feature = feature.to(device)
    label = label.to(device)
    output = model(feature)
    label = label.long()
    # loss :

    loss = loss_fn(output,label)
    # backward pass :
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  total_epochs = total_epochs + loss.item()
  avg_loss = total_epochs / len(train_loader)
  print(f" epochs : {epoch+1} Avg loss :{avg_loss}")

# evaluation
model.eval()

# evaluation code
total = 0
correct = 0

with torch.no_grad():

  for features, labels in test_loader:
    features = features.to(device)
    labels = labels.to(device)

    outputs = model(features)

    _, predicted = torch.max(outputs, 1)

    total += labels.size(0)

    correct = correct + (predicted == labels).sum().item()

print(100*correct/total)

# evaluation code
total = 0
correct = 0

with torch.no_grad():

  for features, labels in train_loader:
    features = features.to(device)
    labels = labels.to(device)

    outputs = model(features)

    _, predicted = torch.max(outputs, dim=1)

    total = total + labels.size(0)

    correct = correct + (predicted == labels).sum().item()

print(100 * correct/total)
