# -*- coding: utf-8 -*-
"""spam classification NLTK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRiBep9OVbDhXOHk9uILwxhUw6G8Pyx4
"""

import nltk
nltk.download('all')

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import pandas as pd

data = {
    'text': [
        'Congratulations you won a free iPhone',
        'Claim your lottery prize now',
        'Win cash reward by clicking this link',
        'Exclusive offer limited time only',
        'Get free recharge instantly',
        'Hi how are you doing today',
        'Meeting scheduled at 10 am tomorrow',
        'Please send the project report',
        'Happy birthday have a great day',
        'Let us discuss the assignment'
    ],
    'label': [  1,1,1,1,1,
                 0,0,0,0,0
              ]
}
df = pd.DataFrame(data)

lemma = WordNetLemmatizer()

def preprocess(text):
    words = word_tokenize(text.lower())
    words = [lemma.lemmatize(word) for word in words if word.isalpha()]
    words = [word for word in words if word not in stopwords.words('english')]
    return " ".join(words)

df['analyse'] = df['text'].apply(preprocess)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

vectorize = TfidfVectorizer()
data = vectorize.fit_transform(df['analyse'])
target = df['label']

x_train,x_test,y_train,y_test = train_test_split(data,target,test_size=0.2,random_state=42)

model = MultinomialNB()

model.fit(x_train,y_train)

y_pred = model.predict(x_test)

while True:
    email = input("\nEnter Email Text (type 'exit' to quit): ")
    if email.lower() == "exit":
        print("Program Closed Successfully.")
        break
    processed_email = preprocess(email)
    email_vector = vectorize.transform([processed_email])
    prediction = model.predict(email_vector)
    if prediction[0] == 1:
        print("SPAM EMAIL")
    else:
        print("NOT SPAM EMAIL")
